-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "comments_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "quotes_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "reposts_count" INTEGER NOT NULL DEFAULT 0;
